import type { NextPage } from "next";
import Image from "next/image";
import styles from "./frame-component.module.css";

export type FrameComponentType = {
  className?: string;
};

const FrameComponent: NextPage<FrameComponentType> = ({ className = "" }) => {
  return (
    <section className={[styles.frameParent, className].join(" ")}>
      <Image
        className={styles.chatgptImageJun19202609}
        width={510}
        height={510}
        alt=""
        src="/hero-img.png"
      />
      <Image
        className={styles.frameChild}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameItem}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameInner}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameIcon}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild2}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild3}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild4}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild5}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild6}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild7}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild8}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />

      <Image
        className={styles.frameChild9}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild10}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />
      <Image
        className={styles.frameChild11}
        loading="lazy"
        width={123}
        height={123}
        sizes="100vw"
        alt=""
        src="/Frame-2087325062@2x.png"
      />

    </section>
  );
};

export default FrameComponent;
